### ISSUE TITLE
Add harmonize root directory parser + configuration file.

### ISSUE THREAD

**Issue by lcszc** [perrystreetsoftware/Harmonize#14]
AFAIK we can't retrieve the project's root directory as we can do on JVM projects, instead we can do something similar to SwiftLint by forcing the creation of an YAML config file and traversing the directories.

The YAML file can be simple as:

```YAML
includes:
  - Folder
  - SomeOtherFolder
excludes:
  - Tests
  ````
  
  Harmonize scope creator tho will still parse unmentioned targets.
